PEGASUS_PATH="${PEGASUS_PATH:-$HOME/.local/share/pegasus}"
[ -f "$PEGASUS_PATH/defaults/bash/rc" ] && source "$PEGASUS_PATH/defaults/bash/rc"

# Editor used by CLI
export EDITOR="nvim"
export SUDO_EDITOR="$EDITOR"
